import { CSSProperties } from "react";

const UserProfileStyles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "#222",
    color: "#ffcc00",
    minHeight: "100vh",
    padding: "2rem",
  },
  title: {
    fontSize: "1.8rem",
    color: "#ffcc00",
    textAlign: "center",
    marginBottom: "1rem",
  },
  form: {
    width: "100%",
    maxWidth: "500px",
    display: "flex",
    flexDirection: "column",
    gap: "1rem",
  },

  inputWrapper: {
    position: "relative",
    width: "100%",
  },
  showPasswordButton: {
    position: "absolute",
    right: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    backgroundColor: "transparent",
    border: "none",
    color: "#ffcc00",
    cursor: "pointer",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "space-between",
    gap: "1rem",
    width: "100%",
  },
  button: {
    flex: 1,
    padding: "0.75rem",
    borderRadius: "4px",
    border: "none",
    cursor: "pointer",
    textAlign: "center",
  },

  modalContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
  },
  passwordContainer: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "1rem",
    width: "80%", // Ajusta según el tamaño que desees
    margin: "0 auto",
  },
  input: {
    width: "100%",
    padding: "0.5rem",
    borderRadius: "4px",
    border: "1px solid #ccc",
    backgroundColor: "#333",
    color: "#fff",
    fontSize: "1rem",
  },
  showButton: {
    position: "absolute",
    right: "10px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "transparent",
    border: "none",
    color: "#ffcc00",
    cursor: "pointer",
    fontSize: "0.9rem",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "center",
    gap: "1rem",
    marginTop: "2rem",
  },
  saveButton: {
    backgroundColor: "#4CAF50",
    color: "#fff",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "1rem",
  },
  cancelButton: {
    backgroundColor: "#f44336",
    color: "#fff",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "1rem",
  },
  modalButton: {
    backgroundColor: "#ffcc00",
    color: "#000",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    width: "100%",
    marginBottom: "1rem",
  },
  editButton: {
    backgroundColor: "#007bff",
    color: "#fff",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    width: "100%",
    marginBottom: "2rem",
  },
  uploadButton: {
    backgroundColor: "#007bff",
    color: "#fff",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    width: "100%",
  },
  uploadButtonDisabled: {
    backgroundColor: "#ccc",
    color: "#fff",
    padding: "0.75rem 1.5rem",
    border: "none",
    borderRadius: "5px",
    cursor: "not-allowed",
    width: "100%",
  },
  emailAdvice: {
    fontSize: "0.9rem",
    color: "#ffcc00",
    marginTop: "-0.5rem",
    marginBottom: "1.5rem",
  },
};

export default UserProfileStyles;
